version: 1.0.0.{build}
image: Visual Studio 2017

branches:
  only:
    - master

build_script:
- cmd: mkdir artifacts
- cmd: nuget pack InnoSetup.nuspec -o artifacts

after_test:
  - cmd: appveyor PushArtifact artifacts\*.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: mDwn5Rqiu4ys9luHvWQo7AAd99VmHiApFyS/lrZhTvdnMj1IA/HiYb2LVeet3Vet
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master

